# Default config file for ServerMOTD


# Broadcast message when the MOTD is changed?
Broadcast: true

# If Broadcast = true, what will the server broadcast when the MOTD is changed?
BroadcastMessage: The Message of the day has been changed! Use /motd read to view it!
